services:
    authors-service: 
        image: khawlarouiss/docker-microservices:authors
        container_name: authors-service
        ports:
            - "8082:8082"
        restart: always   